### ISSUE TITLE
Make the API for changing ECDSAValidator owner more intuitive

### ISSUE THREAD

**Issue by derekchiang** [zerodevapp/sdk#1]
[The API right now](https://github.com/zerodevapp/aa-sdk/tree/8941c66e10dc0742aa1f5d99263cccfc7eb17bd8#change-kernel-account-owner-ecdsavalidator-as-default-validator) works but it's not very intuitive.  We should have a higher-level API on top of this low-level API that's more intuitive.

**Comment by SahilVasava** [comment]
I understand the point. The linked pull request with a restructured, higher-level API in line with your suggestions fixes it. Let me know if it does the trick or not.

**Comment by SahilVasava** [comment]
Closing this issue!
