### ISSUE TITLE
Please support permissionless.js >=0.2.0

### ISSUE THREAD

**Issue by johanneskares** [zerodevapp/sdk#191]
I can't update Viem & permissionless to the latest version, since it's not supported by the Zerodev SDK. Here's the migration guide:

https://docs.pimlico.io/permissionless/how-to/migration-guide

Thanks!

**Comment by jieliu218** [comment]
Same issue. Please support permissionless.js >=0.2.0

**Comment by SahilVasava** [comment]
Hey @jieliu218 and @johanneskares, the latest `5.4.x` update eliminates the need for `permissionless`. 🎉

It now uses `viem@^2.21.40`, which aligns with the updates introduced in `permissionless >=0.2.0`.  🚀
