### ISSUE TITLE
Need to specify dependencies for alpha sdk

### ISSUE THREAD

**Issue by JamesWarbler** [zerodevapp/sdk#20]
Repro repo at https://github.com/JamesWarbler/zdbugreport commit 71dfa2cd5ee76929dd5c05a823af035eecf53883

Getting error:

    Cannot find module '@ethersproject/providers' from 'node_modules/@zerodevapp/sdk/dist/cjs/kernel-zerodev/utils.js'

When I run the test with ```ZERODEV_PROJECT_ID=someId yarn test```

**Comment by uneeb123** [comment]
Just install `yarn add @ethersproject/providers`
