### ISSUE TITLE
error 4.0.32 - 4.0.33: Module not found: Can't resolve '@turnkey/http'

### ISSUE THREAD

**Issue by lanlin** [zerodevapp/sdk#54]
```shell
./node_modules/.pnpm/@zerodev+sdk@4.0.33_typescript@5.2.2/node_modules/@zerodev/sdk/dist/esm/kernel-zerodev/owner/getCustodialOwner.js
Module not found: Can't resolve '@turnkey/http'
```

**Comment by KONFeature** [comment]
the dependencies to use turnkey has changed from: 
`"@turnkey/ethers": "^0.16.5",`

To: 
`
    "@turnkey/api-key-stamper": "^0.1.1",
    "@turnkey/http": "^1.2.0",
    "@turnkey/viem": "^0.2.4",
`

I don't know if the doc has been updated, but you can see the change here: https://github.com/zerodevapp/sdk/commit/88246515c3c0908389c6013e00f1ab18dfeb5271#diff-6291b945f27866157957b6b8227700cc5dfd64b460379ef867723ee5100a49d2

**Comment by lanlin** [comment]
@KONFeature thanks bro
