### ISSUE TITLE
Incompatible with `@turnkey/http` v2

### ISSUE THREAD

**Issue by wottpal** [zerodevapp/sdk#60]
The [Passkey example](https://docs.zerodev.app/create-wallets/passkey) is no longer working with the most recent version of `@turnkey/http`.

![CleanShot 2023-11-07 at 13 13 21@2x](https://github.com/zerodevapp/sdk/assets/3930150/1710b505-8e15-48b7-9613-0a4b769dae28)

**Comment by KONFeature** [comment]
Yep, waiting for this PR to be merged to be compatible with turnkey v2: https://github.com/zerodevapp/sdk/pull/56

**Comment by peripheralist** [comment]
thanks @KONFeature , any idea when the PR will be merged? Is there a workaround you could recommend using in the meantime? I've tried installing "@turnkey/http": "^1.2.0" as specified in the zerodev sdk package.json devDependencies (I suppose it should be a _dependency_?) but seeing this error:
> `Error: Cannot find module '/.../node_modules/@turnkey/http/dist/webauthn' imported from /.../node_modules/@zerodev/sdk/dist/esm/kernel-zerodev/owner/passkey/getPasskeyOwner.js
Did you mean to import @turnkey/http/dist/webauthn.js?`

**Comment by KONFeature** [comment]
Unfortunately no, I'm not from the ZeroDev team and thus I don't know when they will be able to merge it :/

At frak we are using turnkey dependencies for custodial owner of ECDSA wallets, and to fix the issue (and some performance downside of the sdk), we are using the turnkey SDK directly, once we got our turnkey viem account we build a `SmartAccountSigner` compatible with alchemy AA, and provide that owner to the `ECDSAProvider`.

On a very high level point of view it's look like this:


```
export class TurnkeyRepository {

      // A few config & caching stuff
      
    /**
     * Get the SmartAccountSigner account for a given privKey
     * @param privateKeyId
     */
       public async getSigner({
        privateKeyId,
    }: {
        privateKeyId: string;
    }): Promise<SmartAccountSigner> {
        // Logic stuff to build the turnkey viem account, on our side using turnkey api stamper, http & viem
        // createAccount from turnkey/viem
        const account = await createAccount({
            client: this.turnKeyClient,
            organizationId: this.organizationId,
            signWith: privateKeyId,
            ethereumAddress,
        });
        
                // Return the signer
        return {
            signerType: "turnKey",
            getAddress: async () => account.address,
            signMessage: async (msg) => {
                if (typeof msg === "string") {
                    // If the msg is a string, sign it directly
                    return account.signMessage({ message: msg });
                } else {
                    // Otherwise, sign the raw data
                    return account.signMessage({ message: { raw: msg } });
                }
            },
            signTypedData: async (params) => account.signTypedData(params),
        };
    }
}
```

And then, to use zerodev ecdsa provider: 

```
       const eoaAccount = await this.turnKeyRepository.getSigner({
           privateKeyId: zeroDevPrivKeyId,
       });
       
        // Build the smart account
        const smartWallet = await ECDSAProvider.init({
            projectId: this.zeroDevProjectId,
            owner: eoaAccount,
            bundlerProvider: ZERO_DEV_BUNDLER,
            opts: {
                paymasterConfig: {
                    policy: "VERIFYING_PAYMASTER",
                },
                accountConfig: {
                    chain: isRunningInProd() ? polygonMumbai : polygon,
                    accountAddress: address,
                },
            },
        });
```

**Comment by blakecduncan** [comment]
Hey @KONFeature @peripheralist Sorry for the delay but the PR has now been merged

**Comment by peripheralist** [comment]
Hey @KONFeature @blakecduncan , after updating to @zerodev/sdk 4.3.3, i'm still getting the same error :/

```
"@turnkey/api-key-stamper": "^0.1.1",
"@turnkey/http": "^2.1.0",
"@turnkey/viem": "^0.2.4",
```
    
After installing the above dependencies per the zerodev package.json, I see:

`Error: Cannot find module '/.../node_modules/@turnkey/http/dist/webauthn' imported from /.../node_modules/@zerodev/sdk/dist/esm/kernel-zerodev/owner/passkey/getPasskeyOwner.js
Did you mean to import @turnkey/http/dist/webauthn.js`

_Not_ installing those dependencies causes a runtime error "cannot resolve <package>" even though they're listed as devDependencies.

**Comment by blakecduncan** [comment]
@peripheralist Apologies, I am a little backlogged right now but I should be able to get to this early next week.

**Comment by peripheralist** [comment]
thanks @blakecduncan , any updates? i'd be happy to take on a PR if this is still on hold
