### ISSUE TITLE
SyntaxError: The requested module 'permissionless' does not provide an export named 'walletClientToCustomSigner'

### ISSUE THREAD

**Issue by francelwebdev** [zerodevapp/sdk#88]
node_modules/@zerodev/sdk/utils.ts:1
import { walletClientToCustomSigner } from "permissionless"
         ^

SyntaxError: The requested module 'permissionless' does not provide an export named 'walletClientToCustomSigner'

**Comment by derekchiang** [comment]
hi @francelwebdev, can you update to the latest SDK version (`^5.0.5`) which fixes this issue?
