### ISSUE TITLE
[Bug-Error]-creating-smart-account

### ISSUE THREAD

**Issue by nico-limo** [zerodevapp/sdk#89]
Hello, I am following the steps to have a kernelClient so the users will be able to use my App but I am getting this error on my terminal when I add createKernelAccount abd reload the page. I use bun as package Manager

[Create Account](https://docs.zerodev.app/sdk/core-api/create-account)
![image](https://github.com/zerodevapp/sdk/assets/74354611/99665196-ea4f-4031-82fc-834697865430)

If I added without refreshing the website, get this error but maybe because I can't do a writeContract function?
![image](https://github.com/zerodevapp/sdk/assets/74354611/7f2d9ae7-948a-44ef-98b0-4d9c54172d9b)

The method is on a separted folder where I handle web3Methods

```ts
import { signerToEcdsaValidator } from "@zerodev/ecdsa-validator"
import { createKernelAccount, createKernelAccountClient } from "@zerodev/sdk"
import { createPublicClient, Hex, http } from "viem"
import { privateKeyToAccount } from "viem/accounts"
import { polygonMumbai } from "viem/chains"

import { memeMulticallAbi } from "./abis/memeMulticall"
import { memeRouterAbi } from "./abis/memeRouter"
import { ADDRESS_ZERO, CONTRACTS } from "./constants"
const publicClient = createPublicClient({
  chain: polygonMumbai,
  transport: http(),
})


export const createMeme = async ({
  account,
  amount,
  name,
  symbol,
  uri,
}: {
  account: ADDRESS
  amount: bigint
  name: string
  symbol: string
  uri: string
}) => {
  const privateKey = process.env.NEXT_PUBLIC_API_KEY
  const signer = privateKeyToAccount(privateKey as Hex)

  const ecdsaValidator = await signerToEcdsaValidator(publicClient, {
    signer,
  })

  const accountClient = await createKernelAccount(publicClient, {
    plugins: {
      validator: ecdsaValidator,
    },
  })

  const kernelClient = createKernelAccountClient({
    account: accountClient,
    chain: polygonMumbai,
    transport: http(
      `https://rpc.zerodev.app/api/v2/bundler/${process.env.NEXT_PUBLIC_BUNDLE_ID}`
    ),
  })

  // Simulate the method that I want to call
  const { request } = await publicClient.simulateContract({
    address: CONTRACTS.memeRouter,
    abi: memeRouterAbi,
    functionName: "createMeme",
    args: [name, symbol, uri],
    value: amount,
    account,
  })
  console.log(request)
  const tx = await kernelClient.writeContract(request)
  console.log("tx ", tx)
}

```

**Comment by nico-limo** [comment]
If I install permissionless I got now this error
`SyntaxError: The requested module 'permissionless' does not provide an export named 'walletClientToCustomSigner'`
   "permissionless": "^0.0.34",
       "@zerodev/ecdsa-validator": "^5.0.2",
    "@zerodev/presets": "^5.1.1",
    "@zerodev/sdk": "^5.0.4",

**Comment by derekchiang** [comment]
Hi @nico-limo, can you update to the latest version of the SDK?
